# Integrantes: 
# ENZO TREVISAN RM94745
# KAREN MASTROGIACOMO ANTIQUEIRA RM94488  
# KARINA MEGUMI SAKAMOTO RM95121  
# THIAGO MARTINS PRADO RM94426 
# VINÍCIUS RENAN BENJAMIM AOYAGUI RM93386

from functions_stats import handleHomeMenu

handleHomeMenu()